<?php

// Generated by Haxe 3.3.0
class thx_error_ErrorWrapper extends thx_Error {
	public function __construct($message, $innerError, $stack = null, $pos = null) {
		if(!php_Boot::$skip_constructor) {
		parent::__construct($message,$stack,$pos);
		$this->innerError = $innerError;
	}}
	public $innerError;
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	function __toString() { return 'thx.error.ErrorWrapper'; }
}
